### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by CodeLife2012** [sunnyxx/libffi-iOS#2]
Only headers and static lib are  included, somebody may want to investigate the source code.

And static library is  not compatible with [`use_frameworks `](https://github.com/CocoaPods/CocoaPods/issues/3267), can you second think about this?

**Comment by stephenwzl** [comment]
@CodeLife2012 i've found  the correct source code & built it into a dynamic library, you can close this issue

**Comment by stephenwzl** [comment]
@CodeLife2012 https://github.com/stephenwzl/ffi-ios
